Change the value used in bam-test
chrovis/cljam pull request #266
Opened 2022-11-16 11:21 UTC by matsutomo81

Current `cljam.io.bam-test` fails when run with JDK 19. This PR will fix `cljam.io.bam-test` to work regardless of JDK version.
Accordiing to [this release note](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8291475) related to JDK 19, the result of `Float.toString(float)` evaluation may change from previous releases. The value of `1.17549435E-38`, which is used in current test, is affected by this and It causes test failures. This PR resolves the problem by avoiding the use of `1.17549435E-38`.

2022-11-17 03:57 UTC, matsutomo81 commented
By referring to the log below, you can see that the current test fails on Java 19.
https://github.com/chrovis/cljam/actions/runs/3485121567/jobs/5830364082#step:7:305

2022-11-17 05:09 UTC, alumi requested changes
As I commented before, `(= ?value ?value)` doesn't check anything.
Fix the assertion first, then update the test cases. The linter warnings will be also resolved.

2022-11-17 05:15 UTC, alumi commented
Uh, I see. `(= ?value ?value)` doesn't concern array types. Anyway, you can fix it in this PR since the goal of making the `cljam.io.bam-test` work properly is the same 👍

2022-11-17 05:32 UTC, alumi commented on .github/workflows/main.yml
> +        java: [ '8', '11', '16', '17-ea', '19']
LTS versions and the latest

```suggestion
        java: [ '8', '11', '17', '19']
```

2022-11-17 07:48 UTC, alumi approved these changes
LGTM 👍

2022-11-17 08:25 UTC, alumi commented
I just changed the setting of reviewers assignment from load balancing to round robin and redrew a reviewer.

2022-11-28 03:17 UTC, niyarin approved these changes
LGTM. 
Sorry for the late review.

2022-11-28 04:48 UTC, merged